### ISSUE TITLE
Why no Vundle install?

### ISSUE THREAD

**Issue by reggi** [baopham/vundle-cli#1]

**Comment by baopham** [comment]
Because it's already very easy to install a plugin by putting one line in your `vimrc` and run `:PluginInstall`.

And sometimes you might want to put `Plugin my-plugin` in a specific line for better organization. It'd be faster to just open your `vimrc` then.

**Comment by pynixwang** [comment]
yes, we need vundle install 'someplugin'

**Comment by baopham** [comment]
ok. I'll take a look at it this weekend

**Comment by pynixwang** [comment]
done by appending 'Plugin xxx' to line 'call vundle#begin()' and  running `vim +PluginInstall +qall`
